Dynamic -OnChange- task rendering.
SarAhmed/timeline-dep-graph pull request #7
Opened 2020-09-28 15:36 UTC by SarAhmed

- Created Task interface.
- Create Item interface.
- Rendered tasks in the timeline
   - Add
   - Remove
   - Update

![image](https://user-images.githubusercontent.com/46672501/94454571-4fd38200-01b2-11eb-8eb1-d6af9be24b88.png)

2020-09-29 08:11 UTC, iguru-google requested changes
Consider moving the demo in a separate path, so you only keep the component itself in src. This is not necessary now.

2020-09-29 12:00 UTC, MW1245 requested changes
Please include a short comment for each exported item.

2020-09-29 14:19 UTC, MW1245 approved these changes

2020-09-29 14:30 UTC, iguru-google approved these changes

2020-09-29 14:31 UTC, merged

2020-10-23 08:06 UTC, SarAhmed commented on timeline-dep-graph/src/app/app.component.ts
> +      }, 2000);
#22

2020-10-23 08:06 UTC, SarAhmed commented on timeline-dep-graph/src/app/app.component.ts
> +      const tasksDemo2 = [ // Test Add
Implemented in: #22

2020-10-23 08:07 UTC, SarAhmed commented on timeline-dep-graph/src/app/app.component.ts
> +      this.cdRef.detectChanges();
Implemented in: #22

2020-10-23 08:07 UTC, SarAhmed commented on timeline-dep-graph/src/app/app.component.ts
> +  ngAfterViewInit(): void {
Implemented in: #22